[phases.setup]
nixPkgs = [
  "libwebp",
  "pkg-config",
  "cairo",
  "pango",
  "libjpeg",
  "giflib",
  "librsvg",
  "pixman",
  "python3",
  "gcc",
  "gnumake"
]

[phases.install]
cmds = ["npm ci", "npm rebuild canvas --build-from-source"]
